import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome Back</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <li>Home</li>
        </ul>
        <ul>
          <li>About</li>{" "}
        </ul>
        <ul>
          <li>Blog</li>
        </ul>
        <ul>
          <li>Contact us</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1>
          <a>Welcome to Abhishek's Blog post 🙏</a>
        </h1>

        <p className={styles.description}>
          you can all types of javascripit interview problem solution
        </p>

        <div>
          <h2>Popular Blog of JS</h2>
          <div className="blogs">
            <h3>difference between == and ===</h3>
            <p>
              == only comapre the value where === comapre value as well as type
            </p>
          </div>
          <div className="blogs">
            <h3>difference between == and ===</h3>
            <p>
              == only comapre the value where === comapre value as well as type
            </p>
          </div>
          <div className="blogs">
            <h3>difference between == and ===</h3>
            <p>
              == only comapre the value where === comapre value as well as type
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
